title: <p align="center"> Mayank Aditya </p>
logo: /assets/img/Cropped.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mayankaditya/">LinkedIn</a> |
  <a href="https://github.com/mayankaditya07/">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Amazon Competitive Pricing Team for 5 years.
  Currently Working in Amazon Finance team as Business Intelligence Enginner for last 1 month.
  <br>
  </p>



theme: jekyll-theme-minimal
